# Generated by Django 4.2.9 on 2024-02-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pojazd",
            name="moc",
        ),
    ]
