# Generated by Django 4.2.9 on 2024-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0002_remove_pojazd_moc"),
    ]

    operations = [
        migrations.AddField(
            model_name="pojazd",
            name="moc",
            field=models.FloatField(default=0),
        ),
    ]
