# Generated by Django 4.2.9 on 2024-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0003_pojazd_moc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pojazd",
            name="rok_produkcji",
            field=models.DateField(default="2000"),
        ),
    ]
