# Generated by Django 4.2.9 on 2024-02-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0004_alter_pojazd_rok_produkcji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pojazd",
            name="rok_produkcji",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
