# Generated by Django 4.2.9 on 2024-02-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0005_alter_pojazd_rok_produkcji"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pojazd",
            name="rok_produkcji",
        ),
        migrations.AddField(
            model_name="pojazd",
            name="rok_wytworzenia",
            field=models.CharField(default=2022, max_length=4),
            preserve_default=False,
        ),
    ]
