# Generated by Django 4.2.9 on 2024-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0006_remove_pojazd_rok_produkcji_pojazd_rok_wytworzenia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Karty_paliwowe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nr_karty", models.CharField(max_length=20)),
                ("nr_rejestracyjny", models.CharField(max_length=20)),
                ("data_waznosci", models.DateField()),
                ("kod_pin", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="TowarzystwoUbezpieczeniowe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nazwa_Towarzystwa", models.CharField(max_length=255)),
                ("adres_ulica", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Warsztat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nazwa", models.CharField(max_length=255)),
                ("adres_ulica", models.CharField(max_length=255)),
                ("adres_miasto", models.CharField(max_length=255)),
                ("adres_kod_pocztowy", models.CharField(max_length=20)),
                ("nip", models.CharField(max_length=10)),
                ("regon", models.CharField(max_length=9)),
                ("telefon", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=255)),
                ("www", models.CharField(max_length=255)),
                ("osoba_kontaktowa", models.CharField(max_length=255)),
            ],
        ),
    ]
