# Generated by Django 4.2.9 on 2024-02-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0007_karty_paliwowe_towarzystwoubezpieczeniowe_warsztat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Karty_paliwowe",
            new_name="Karta_paliwowa",
        ),
    ]
