# Generated by Django 4.2.9 on 2024-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0008_rename_karty_paliwowe_karta_paliwowa"),
    ]

    operations = [
        migrations.AddField(
            model_name="karta_paliwowa",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("AKTYWNA", "Aktywna"), ("ZABLOKOWANA", "Zablokowana")],
                max_length=20,
                null=True,
            ),
        ),
    ]
