# Generated by Django 4.2.9 on 2024-02-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0009_karta_paliwowa_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="karta_paliwowa",
            old_name="data_waznosci",
            new_name="data_ważności",
        ),
        migrations.AddField(
            model_name="karta_paliwowa",
            name="limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C_3/60+120", "C_3/60+120"),
                    ("C_3/60+120+AutoGaz", "C_3/60+120+AutoGaz"),
                    ("C_1/75+120", "C_1/75+120"),
                    ("C_1/600+120", "C_1/600+120"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="karta_paliwowa",
            name="typ_kary",
            field=models.CharField(
                blank=True,
                choices=[("KIEROWCA", "Kierowca"), ("SAMOCHOD", "Samochód")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pojazd",
            name="karty_paliwowe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FleetManagement.karta_paliwowa",
            ),
        ),
    ]
