# Generated by Django 4.2.9 on 2024-02-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "FleetManagement",
            "0010_rename_data_waznosci_karta_paliwowa_data_ważności_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="karta_paliwowa",
            old_name="typ_kary",
            new_name="typ_karty",
        ),
    ]
