# Generated by Django 4.2.9 on 2024-02-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0011_rename_typ_kary_karta_paliwowa_typ_karty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pojazd",
            old_name="karty_paliwowe",
            new_name="karta_paliwowa",
        ),
    ]
