# Generated by Django 4.2.9 on 2024-02-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0012_rename_karty_paliwowe_pojazd_karta_paliwowa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uzytkownik",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("imie", models.CharField(max_length=255)),
                ("nazwisko", models.CharField(max_length=255)),
                ("stanowisko", models.CharField(max_length=255)),
                ("nr_rej_samochodu", models.CharField(max_length=20)),
                (
                    "mpk",
                    models.IntegerField(
                        choices=[
                            (2000, "2000- KOSZTY POŚREDNIE PRODUKCJI"),
                            (2100, "2100- KOSZTY UTRZYMANIA RUCHU"),
                            (2200, "2200-KOSZTY NADZORU PRODUKCYJNEGO"),
                            (2210, "2210-KOSZTY GŁÓWNEGO SPAWALNIKA"),
                            (2230, "2230-KOSZTY WŁASNYCH SZKOLEŃ I PRAKTYK"),
                            (3300, "3300-KOSZTY NARZĘDZIOWNI"),
                            (4000, "4000-KOSZTY DZIAŁU KONTROLI WEWNĘTRZNEJ"),
                            (5100, "5100-DYREKTOR DS.HANDLOWYCH"),
                            (5110, "5110-KOSZTY DZIAŁU OFERTOWEGO"),
                            (5120, "5120-KOSZTY DZIAŁU HANDLOWEGO"),
                            (5200, "5200-KOSZTY DZIAŁU ZAKUPOW"),
                            (5300, "5300-KOSZTY DZIALU MARKETINGU"),
                            (5400, "5400-KOSZTY GOSPOD.MATER., LOGISTYKI I SPEDYCJI"),
                            (
                                6100,
                                "6100-DYREKTOR DS. PRODUKCJI, DS. PRZYGOT.I REALIZ.PRODU",
                            ),
                            (6110, "6110-KOSZTY DZIAŁU PRODUKCJI"),
                            (6120, "6120-KOSZTY DZIAŁU PRZYGOTOWANIA"),
                            (6130, "6130-KOSZTY DZIAŁU REALIZACJI"),
                            (6200, "6200-KOSZTY DZIAŁU PLANOWANIA I CYFRYZACJI"),
                            (6300, "6300-KOSZTY DZIAŁU TECHNICZNEGO"),
                            (6410, "6410-KOSZTY DZIALU MONTAZOWEGO"),
                            (6500, "6500-KOSZTY LABORATORIUM"),
                            (6510, "6510-KOSZTY DZIAŁU KONTROLI JAKOŚCI"),
                            (
                                6520,
                                "6520-KOSZTY DZIALU ZAPEWN.JAKOŚCI, BHP I OCHRONY ś",
                            ),
                            (6600, "6600-KOSZTY DZIAŁU INWESTYCJI"),
                            (6700, "6700-KOSZTY Z-CY DYREKTORA DS. TECHNOLOGII"),
                            (7000, "7000-KOSZTY RADY NADZORCZEJ"),
                            (7100, "7100-KOSZTY ZARZĄDU"),
                            (7110, "7110-KOSZTY BIURA ZARZĄDU"),
                            (7120, "7120-KOSZTY DORADCÓW ZARZADU"),
                            (7300, "7300-KOSZTY OBSŁUGI PRAWNEJ"),
                            (7310, "7310-KOSZTY DZIAŁU UMÓW"),
                            (7400, "7400-KOSZTY DZIAŁU FINANSOWO - KSIĘGOWEGO"),
                            (7510, "7510-KOSZTY DZIAŁU KONTROLINGU"),
                            (7600, "7600-KOSZTY WYDZIALU ADMINISTRACYJNEGO"),
                            (7700, "7700-KOSZTY DZIAŁU INFORMATYKI"),
                            (7800, "7800-KOSZTY DZIAŁU PŁAC I ZZL"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pojazd",
            name="mpk",
        ),
        migrations.RemoveField(
            model_name="pojazd",
            name="uzytkownik",
        ),
    ]
