# Generated by Django 4.2.9 on 2024-02-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0014_uzytkownik_pojazd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uzytkownik",
            name="pojazd",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FleetManagement.pojazd",
            ),
        ),
    ]
