# Generated by Django 4.2.9 on 2024-02-29 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FleetManagement", "0015_alter_uzytkownik_pojazd"),
    ]

    operations = [
        migrations.AddField(
            model_name="pojazd",
            name="uzytkownik",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pojazd_relation",
                to="FleetManagement.uzytkownik",
            ),
        ),
        migrations.AlterField(
            model_name="uzytkownik",
            name="pojazd",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uzytkownik_relation",
                to="FleetManagement.pojazd",
            ),
        ),
    ]
